// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfqzredybxztnvwbqckh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmcXpyZWR5Ynh6dG52d2JxY2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3MTE4OTYsImV4cCI6MjA4NzI4Nzg5Nn0.jNTgEXGSKlRXSrvDfe9hWkl3NbTkPRC7JznDaT6zJa8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});